# Generated by Django 4.2.6 on 2023-12-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_introvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('body', models.CharField(max_length=500)),
                ('time_posted', models.CharField(max_length=50)),
                ('views', models.CharField(blank=True, max_length=5, null=True)),
                ('likes', models.CharField(blank=True, max_length=5, null=True)),
                ('comments', models.CharField(blank=True, max_length=5, null=True)),
                ('share', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
