# Generated by Django 4.2.8 on 2023-12-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
