# Generated by Django 4.2.8 on 2023-12-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_frontpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
