# Generated by Django 4.2.8 on 2023-12-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_frontpage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUseAgki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
